In [1]:
#import all required libraries
import pandas as pd
import time
import cv2 
from skimage.feature import hog
from sklearn import svm
from sklearn.model_selection import GridSearchCV
import os
import matplotlib.pyplot as plt
from skimage.transform import resize
from skimage.io import imread
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
import pickle

C:\Users\faisal javed\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

### train with orignal images

In [5]:
""""
img_resized=resize(128,64,3)
        #on load tha dataset 
data_flat=[]
indexs_arr=[]
# how much classes in your dataset u should to write that here
Categories=['Cars','Ice cream cone','Cricket ball']
datadir='Image Classification'
for i in Categories:
    print(f'classes loading...====>>>> category_vise  : {i}')
    path=os.path.join(datadir,i)
    for img in os.listdir(path):
        img_array=imread(os.path.join(path,img))
        #imge dimension with flatten
        data_flat.append(img_resized.flatten())
    
        indexs_arr.append(Categories.index(i))
    print(f'loaded categories =====>>>>:{i} successfully')
data_flat=np.array(data_flat)
target=np.array(indexs_arr)
df=pd.DataFrame(data_flat)
df['Target']=target
""""

SyntaxError: EOL while scanning string literal (3752787448.py, line 23)

In [4]:


# Define the image dimensions for resizing
img_shape = (128, 64, 3)

# Define the list to store flattened image data and category index
data_flat = []
indexs_arr = []

# Define the categories in your dataset
Categories = ['Cars', 'Ice cream cone', 'Cricket ball']

# Define the directory where your images are located
datadir = 'Image Classification dataset'

for i in Categories:
    print(f'Loading category: {i}')
    path = os.path.join(datadir, i)
    
    for img in os.listdir(path):
        img_path = os.path.join(path, img)
        img_array = imread(img_path)
        
        # Resize the image to the specified dimensions
        img_resized = resize(img_array, img_shape)
        
        # Flatten the resized image and store it in data_flat
        data_flat.append(img_resized.flatten())
        
        # Store the index of the category in indexs_arr
        indexs_arr.append(Categories.index(i))
    
    print(f'Loaded category: {i} successfully')

# Convert data_flat and indexs_arr to numpy arrays
data_flat = np.array(data_flat)
target = np.array(indexs_arr)

# Create a DataFrame with flattened image data and target labels
df = pd.DataFrame(data_flat)

# Add the 'Target' column with category labels
df['Target'] = target

Loading category: Cars
Loaded category: Cars successfully
Loading category: Ice cream cone
Loaded category: Ice cream cone successfully
Loading category: Cricket ball
Loaded category: Cricket ball successfully

In [ ]:
# # plt.imshow(data_flat[0] , cmap="gray")
# np.unique(indexs_arr)
# np.unique(data_flat)

In [3]:
pd.Series([data_flat]).value_counts()
data_flat.shape
# indexs_arr

NameError: name 'data_flat' is not defined

#### load data and use SIFT EXRACTOR

In [9]:
# # load tha dataset 
# # Set the path to the directory containing  images
# datadir = "Image Classification"

# # Set the parameters for SIFT feature extraction
# sift=cv2.SIFT_create()

# # Create empty lists to store the feature vectors and their labels
# sift_vectors = []
# labels = []

# class_labels=['Cars','Ice cream cone','Cricket ball']
# # Loop over each image in the directory
# for i, class_label in enumerate(class_labels):
#     for file in os.listdir(os.path.join(datadir, class_label)):
#         if file.endswith(".jpg"):
#             # Load the image
#             img = cv2.imread(os.path.join(datadir, class_label, file))
#             gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#             # Extract the SIFT features
#             kp, des = sift.detectAndCompute(gray, None)
#             # Add the feature vector and its label to the list
#             des = np.resize(des,(500,128)).flatten()
#             sift_vectors.append(des)
#             labels.append(i)
          


#  #Convert list to np.array
# sift_vectors = np.array(sift_vectors)

# # Convert list feature to nparray
# labels = np.array(labels)
# df=pd.DataFrame(sift_vectors)
# df['Target']=labels

In [10]:
df

,0,1,2,3,4,5,6,7,8,9,...,63991,63992,63993,63994,63995,63996,63997,63998,63999,Target
0,70.0,14.0,4.0,19.0,24.0,1.0,2.0,9.0,180.0,82.0,...,10.0,113.0,4.0,0.0,1.0,2.0,1.0,0.0,1.0,0
1,4.0,34.0,8.0,1.0,8.0,135.0,27.0,7.0,70.0,100.0,...,0.0,28.0,170.0,7.0,0.0,4.0,37.0,2.0,0.0,0
2,1.0,1.0,5.0,3.0,0.0,0.0,21.0,26.0,39.0,14.0,...,1.0,2.0,48.0,128.0,5.0,0.0,0.0,0.0,2.0,0
3,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,...,73.0,85.0,11.0,3.0,2.0,1.0,11.0,21.0,31.0,0
4,74.0,107.0,35.0,38.0,60.0,2.0,3.0,55.0,3.0,14.0,...,33.0,45.0,85.0,17.0,1.0,3.0,5.0,5.0,18.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
956,149.0,13.0,0.0,0.0,0.0,0.0,0.0,11.0,149.0,18.0,...,0.0,4.0,4.0,52.0,102.0,13.0,5.0,8.0,11.0,2
957,106.0,23.0,0.0,1.0,3.0,0.0,0.0,1.0,177.0,87.0,...,21.0,3.0,12.0,51.0,19.0,51.0,15.0,7.0,11.0,2
958,3.0,1.0,1.0,1.0,10.0,81.0,101.0,51.0,4.0,3.0,...,46.0,1.0,2.0,3.0,16.0,43.0,46.0,23.0,3.0,2
959,39.0,6.0,0.0,0.0,0.0,0.0,0.0,2.0,172.0,17.0,...,18.0,84.0,4.0,0.0,0.0,0.0,0.0,0.0,12.0,2
960,7.0,3.0,0.0,0.0,1.0,6.0,9.0,18.0,150.0,92.0,...,3.0,35.0,62.0,3.0,0.0,13.0,45.0,6.0,3.0,2

### use HOG extractor for feature

In [14]:
# hog_vectors = []
# labels = []
# datadir = "Image Classification"

# # Define HOG parameters
# orientations = 9
# pixels_per_cell = (8, 8)
# cells_per_block = (2, 2)
# block_norm = 'L2-Hys'  ##l2-hysteresis 


# class_labels=['Cars','Ice cream cone','Cricket ball']
# # Loop over each image in the directory
# for i, class_label in enumerate(class_labels):
#     for file in os.listdir(os.path.join(datadir, class_label)):
#         if file.endswith(".jpg"):
#             # Load the image
#             img = cv2.imread(os.path.join(datadir, class_label, file))
#             img=cv2.resize(img , (64, 128))
#             gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#             # Extract the hog features
#             hog_features, hog_image = hog(gray, orientations=orientations, pixels_per_cell=pixels_per_cell, cells_per_block=cells_per_block, block_norm=block_norm, visualize=True)

#             hog_vectors.append(hog_features)
#             labels.append(i)
          

# # Convert list to np.array
# hog_vectors = np.array(hog_vectors)

# # Convert list feature to nparray
# labels = np.array(labels)
# df=pd.DataFrame(hog_vectors)
# df['Target']=labels

In [13]:
df

,0,1,2,3,4,5,6,7,8,9,...,3770,3771,3772,3773,3774,3775,3776,3777,3778,3779
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.128081,0.007505,0.018986,0.013838,0.124457,0.247273,0.247273,0.247273,0.148860,0.182510,...,0.160946,0.111903,0.000000,0.047186,0.017585,0.166828,0.180079,0.193735,0.234831,0.017585
2,0.250852,0.030783,0.046454,0.134957,0.250852,0.189546,0.115172,0.091408,0.236890,0.250852,...,0.053882,0.152314,0.123715,0.062725,0.077988,0.111393,0.043233,0.089356,0.060912,0.052105
3,0.330296,0.103976,0.000000,0.000000,0.056382,0.018915,0.039487,0.188149,0.097372,0.330296,...,0.046886,0.221234,0.206138,0.131709,0.165595,0.158382,0.174222,0.085624,0.069992,0.111786
4,0.401868,0.000000,0.000000,0.004490,0.097532,0.014238,0.034035,0.001379,0.401868,0.394815,...,0.144714,0.144575,0.058260,0.097361,0.182489,0.254830,0.133308,0.061902,0.092690,0.164281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
956,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
957,0.417596,0.000000,0.000000,0.000000,0.417596,0.000000,0.206614,0.000000,0.000000,0.292197,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
958,0.291991,0.000000,0.051529,0.000000,0.163966,0.122213,0.291991,0.285163,0.000000,0.291991,...,0.181584,0.229850,0.191973,0.093722,0.107994,0.126165,0.054534,0.120054,0.152013,0.025119
959,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
960,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

### ORB extractor

In [15]:
from skimage.feature import orb
orb_vectors = []
labels = []
orb = cv2.ORB_create()
class_labels=['Cars','Ice cream cone','Cricket ball']
# Loop over each image in the directory
for i, class_label in enumerate(class_labels):
    for file in os.listdir(os.path.join(datadir, class_label)):
        if file.endswith(".jpg"):
            # Load the image
            img = cv2.imread(os.path.join(datadir, class_label, file))
            img=cv2.resize(img , (64, 128))
            gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
            # Extract the orb features
            keypoints, descriptors = orb.detectAndCompute(img, None)
            descriptors = np.resize(descriptors,(500,128)).flatten()
            orb_vectors.append(descriptors)
            labels.append(i)
          

  #    Convert list to np.array
orb_vectors = np.array(orb_vectors)

# Convert list feature to nparray
labels = np.array(labels)
df=pd.DataFrame(orb_vectors)

df['Target']=labels

In [16]:
df

,0,1,2,3,4,5,6,7,8,9,...,63991,63992,63993,63994,63995,63996,63997,63998,63999,Target
0,154,123,99,136,75,149,190,112,165,132,...,227,154,247,126,251,128,68,143,11,0
1,41,191,185,232,253,141,145,127,203,73,...,142,241,173,162,144,37,170,116,105,0
2,1,206,147,250,116,140,111,254,126,25,...,61,249,225,45,57,32,51,166,74,0
3,42,25,144,237,45,93,208,31,143,41,...,147,247,247,53,191,82,194,143,115,0
4,89,89,85,101,42,74,85,48,96,248,...,63,228,235,116,144,127,152,194,41,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
956,112,169,152,240,56,201,80,7,170,189,...,33,217,235,116,48,160,81,7,122,2
957,4,77,2,157,212,131,174,226,20,128,...,255,52,36,142,0,21,123,113,136,2
958,171,188,161,83,197,253,229,239,95,243,...,194,174,117,47,199,174,246,159,117,2
959,61,63,99,224,246,147,239,113,213,200,...,253,34,40,170,200,23,14,244,221,2
960,43,179,224,155,255,241,186,207,27,125,...,177,62,221,5,127,251,143,94,229,2

In [4]:
df.isnull().values.any().sum()

# replace infinite values with NaN
df = df.replace([np.inf, -np.inf], np.nan)

# drop rows with NaN values
df = df.dropna()

df= df.fillna(0)
df.isnull().values.any().sum()

0

In [1]:
#

In [122]:
# df=np.array(df)

In [81]:
# df = df.reshape((-1, df.shape[-1]))

1

In [5]:

# lets seperate xtrain xtest ytrain ytest data
from sklearn.model_selection import train_test_split
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [13]:
# x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=1)

In [15]:
x_train.shape , x_test.shape

((789, 24576), (198, 24576))

In [11]:
# feature scaling with max and min extra work
# print(x_train.max() , x_train.min())

In [20]:
# # for sift extractor
# x_train,x_test,y_train,y_test=train_test_split(sift_vectors,labels,test_size=0.20,random_state=1)

In [82]:
# # # for hog extractor
# x_train , x_test, y_train, y_test=train_test_split(hog_vectors,labels, test_size=0.20)

In [21]:
# for orb extractor
x_train,x_test,y_train,y_test=train_test_split(orb_vectors,labels,test_size=0.20,random_state=1)

In [14]:
#standarize the data
from sklearn.metrics import accuracy_score, precision_score, recall_score

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()


x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_test
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## logistic

In [4]:
#  now chose the model after finish preprocessing data
# choose model and fitting modele 
from sklearn.linear_model import LogisticRegression

model=LogisticRegression()
start_time=time.time()
model.fit(x_train , y_train)
end_time=time.time()
training_time=end_time - start_time
print("time complexity :{:.3f} ".format(training_time))

y_pred=model.predict(x_test)

ytrain_pred=model.predict(x_train)
print("predicted value",y_pred)
print("actual  value",y_test)
print("accuracy  test time in logistic model ",accuracy_score(y_test, y_pred))
print("accuracy  train time in logistic model ",accuracy_score(y_train, ytrain_pred))
# print("accuracy on traning time " , accuracy_score(y_train, y_pred))

NameError: name 'x_train' is not defined

In [10]:
x_train

array([[-7.93169515e-01, -3.65762944e-01, -4.11378826e-01, ...,
        -6.17535213e-01, -6.52796294e-01, -5.70898225e-01],
       [ 1.25295089e+00,  4.53669803e-01, -4.11378826e-01, ...,
        -4.88715061e-01, -1.43398275e-01,  1.79664870e-02],
       [-7.93169515e-01, -3.65762944e-01, -4.11378826e-01, ...,
        -6.17535213e-01, -6.52796294e-01, -5.70898225e-01],
       ...,
       [-7.93169515e-01, -3.65762944e-01, -4.11378826e-01, ...,
        -6.17535213e-01, -6.52796294e-01, -5.70898225e-01],
       [ 1.45510412e+00,  3.74500435e-02,  1.26419494e+00, ...,
        -4.03690403e-01, -4.00995867e-01,  1.34040026e-01],
       [-5.70772910e-01, -1.86926341e-01, -2.45543220e-01, ...,
        -1.86939938e-01, -1.33516855e-03, -2.60275909e-02]])

## SVM  classifier

In [85]:
# from sklearn.svm import SVC
# # lets seperate xtrain xtest ytrain ytest data


# classifier=SVC(kernel="linear" , random_state=0) ##here we can use kernl linear, poly, sigmoid etc
# # Split data into training and testing sets


# start_time=time.time()
# classifier.fit(x_train , y_train)
# end_time=time.time()
# training_time=end_time - start_time
# print("time complexity :{:.3f} ".format(training_time))
# y_pred=classifier.predict(x_test)
# ytrain_pred=classifier.predict(x_train)
# print("accuracy  train time  svm   ",accuracy_score(y_train, ytrain_pred))
# print("accuracy  test time in SVM   ",accuracy_score(y_test, y_pred))

# # now to find confusion matric
# from sklearn.metrics import confusion_matrix
# cm=confusion_matrix(y_test, y_pred)
# print(cm)

time complexity :0.933
accuracy  train time  svm    1.0
accuracy  test time in SVM    0.9740932642487047
[[65  0  1]
 [ 3 47  0]
 [ 1  0 76]]

### DecisionTreeClassifier

In [86]:
# # now choose model and fitt that  model
# from sklearn.tree import DecisionTreeClassifier
# classifier=DecisionTreeClassifier(criterion="entropy" , random_state=0)
# # start_time=time.time()
# classifier.fit(x_train , y_train)
# end_time=time.time()
# training_time=end_time - start_time
# print("time complexity :{:.3f} ".format(training_time))
# # classifier.score(x_train, y_train)


# y_pred=classifier.predict(x_test)
# print(y_pred)

# ytrain_pred=classifier.predict(x_train)
# print("accuracy  train time random DecisionTreeClassifier   ",accuracy_score(y_train, ytrain_pred))
# print("accuracy  test time in DecisionTreeClassifier   ",accuracy_score(y_test, y_pred))
# from sklearn.metrics import confusion_matrix
# cm=confusion_matrix(y_test , y_pred)
# print(cm)

time complexity :26.573
[0 0 1 2 2 2 2 2 1 2 0 2 2 2 1 2 0 2 2 2 2 0 0 0 0 2 2 2 0 1 2 2 2 0 0 2 2
 0 2 0 2 2 2 2 1 1 0 2 2 2 0 1 2 0 1 1 0 2 1 2 0 0 1 0 2 1 1 2 2 0 2 0 0 2
 0 1 2 2 0 0 0 1 1 1 0 2 0 1 1 0 1 2 2 1 0 2 0 2 0 2 0 1 2 0 1 0 2 2 2 1 2
 1 1 2 0 1 0 0 2 2 0 2 2 1 0 1 1 1 2 1 0 2 2 1 1 0 1 0 0 2 2 1 1 2 1 0 2 0
 2 1 2 0 2 0 1 0 0 0 1 1 1 2 2 2 0 1 1 0 1 0 1 0 0 0 2 2 1 2 2 1 0 2 0 2 2
 2 2 0 1 1 0 2 0]
accuracy  train time random DecisionTreeClassifier    1.0
accuracy  test time in DecisionTreeClassifier    0.7927461139896373
[[50  9  7]
 [ 5 38  7]
 [ 8  4 65]]

### RandomForestClassifier

In [87]:
# now choose model and fitt that  model



from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=10 ,criterion="entropy", random_state=0)


start_time=time.time()
classifier.fit(x_train , y_train)
end_time=time.time()
training_time=end_time - start_time
classifier.score(x_train, y_train)

print("time complexity :{:.3f} ".format(training_time))
# now preedict the test value
y_pred=classifier.predict(x_test)

print(y_pred)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test , y_pred)
print("consusion matric",cm)



print("accuracy  test time random RandomForestClassifier   ",accuracy_score(y_test, y_pred))


ytrain_pred=classifier.predict(x_train)
print("accuracy  train time random RandomForestClassifier   ",accuracy_score(y_train, ytrain_pred))

time complexity :0.523
[0 0 1 2 2 2 0 1 2 2 2 0 2 2 0 2 0 2 2 2 2 0 0 0 0 2 2 1 2 1 2 2 2 0 0 2 2
 0 0 0 1 2 2 2 1 1 0 2 2 2 0 1 2 0 0 1 0 2 0 2 2 0 1 1 2 0 1 2 2 2 1 0 0 2
 0 1 2 0 0 0 0 1 1 1 0 2 0 0 0 0 0 2 2 0 0 2 0 0 0 2 0 1 2 0 1 0 2 2 2 1 0
 1 1 0 0 2 2 0 2 2 0 0 1 1 0 2 1 1 2 1 0 2 2 1 1 0 1 0 2 2 2 0 1 2 1 2 2 0
 0 1 0 0 2 0 1 0 0 2 1 1 0 2 2 2 2 1 1 0 2 0 0 2 0 0 2 2 1 2 2 0 0 2 0 2 0
 0 0 0 1 1 0 2 0]
consusion matric [[62  2  2]
 [ 8 38  4]
 [ 7  1 69]]
accuracy  test time random RandomForestClassifier    0.8756476683937824
accuracy  train time random RandomForestClassifier    0.9986979166666666